fixed SC2155 while keeping the benefits of readonly

diff --git a/stitch b/stitch
--- a/stitch
+++ b/stitch
@@ -36,31 +36,32 @@ declare -ri sector_size=512
 ##########################################################################
 
 # $empty matches a blank line, which is used as a divider (no captures).
-declare -r empty='^$'
+readonly empty='^$'
 
 # These regexes appear as helpers in several of those to follow.
-declare -r num='([0-9]+)'
-declare -r gap=' {2,}'
+readonly num='([0-9]+)'
+readonly gap=' {2,}'
 
 # $intro matches fiemap's first output line (4 captures).
-declare -r device="block device $num:$num"       # capture groups 1 and 2
-declare -r offset="byte $num \\(sector $num\\)"  # capture groups 3 and 4
-declare -r intro="^On $device, which starts at $offset:\$"
+readonly device="block device $num:$num"       # capture groups 1 and 2
+readonly offset="byte $num \\(sector $num\\)"  # capture groups 3 and 4
+readonly intro="^On $device, which starts at $offset:\$"
 
 # $labels matches the table's columns headings (no captures).
-declare -r sec='\(sec\)'
+readonly sec='\(sec\)'
 lab() { printf '%s%s%s' "$gap" "$1" "$sec"; }
-declare -r labels="^$(lab LOGICAL)$(lab INITIAL)$(lab FINAL)$(lab COUNT)\$"
+labels="^$(lab LOGICAL)$(lab INITIAL)$(lab FINAL)$(lab COUNT)\$"
+readonly labels
 
 # $table_row matches a row of the table (4 captures).
-declare -r table_row="^$gap$num$gap$num$gap$num\$"
+readonly table_row="^$gap$num$gap$num$gap$num\$"
 
 # $trivial matches fiemap's last output line for an empty file (no captures).
-declare -r trivial='^There are no extents\.$'
+readonly trivial='^There are no extents\.$'
 
 # $outro matches fiemap's last ouptut line otherwise (4 captures).
 # This is the "outro" or "interpretation guide."
-declare -r outro="^$num/$num bytes used, $num/$num in the last extent\\.\$"
+readonly outro="^$num/$num bytes used, $num/$num in the last extent\\.\$"
 
 
 ##########################################################################
@@ -70,6 +71,7 @@ declare -r outro="^$num/$num bytes used, $num/$num in the last extent\\.\$"
 # Perform the actual IO read. After this, we are iterating an array.
 declare -a lines
 mapfile -t lines
+readonly lines
 declare -ri lc="${#lines}"
 declare -i li=0
 
@@ -131,7 +133,7 @@ if ((${#starts} == 0)); then
 fi
 
 # Parse the outro ("interpretation guide") for a non-empty input file.
-[[ ${lines[li] =~ $outro } ]] || die 'malformed interpretation guide'
+[[ ${lines[li]} =~ $outro ]] || die 'malformed interpretation guide'
 declare -ri used_bytes="${BASH_REMATCH[1]}"
 declare -ri total_bytes="${BASH_REMATCH[2]}"
 declare -ri last_used_bytes="${BASH_REMATCH[3]}"
@@ -159,26 +161,26 @@ parse_end
 ### Attempt to stitch the sectors together by reading physical blocks. ###
 ##########################################################################
 
-declare -r volume="$(find_node "$major" "$minor")" ||
-    die "can't find node for volume $major:$minor"
-
-msg "The volume seems to be $major:$minor ($volume)."
+volume="$(find_node "$dev_major" "$dev_minor")" ||
+    die "can't find node for volume $dev_major:$dev_minor"
+readonly volume
+msg "The volume seems to be $dev_major:$dev_minor ($volume)."
 
 if ((minor == 0)); then
-    declare -r disk="$volume"
+    readonly disk="$volume"
 else
     # TODO: Research if this assumption is really sound.
-    declare -r disk="$(find_node "$major" 0)" ||
-        die "can't find node for disk $major:$minor"
+    disk="$(find_node "$dev_major" 0)" ||
+        die "can't find node for disk $dev_major:$dev_minor"
+    readonly disk
 fi
+msg "The disk seems to be $dev_major:0 ($disk)."
 
-msg "The disk seems to be $major:0 ($disk)."
-
-# TODO: It's reasonable to run a non-root user for the parsing. When getopt
+# TODO: It's reasonable to run as a non-root user, for the parsing. When getopt
 #       support is added, include options to force stopping or continuing here.
 ((EUID == 0)) || die "you're not root; not trying to read blocks"
 
-exec 3<"$disk" || die "can't open device node for disk $major:0"
+exec 3<"$disk" || die "can't open device node for disk $dev_major:0"
 
 ((0 < ${#starts})) || bug 'no blocks'
 
@@ -191,7 +193,7 @@ done
 
 # Read as many used full sectors as possible from the last extent.
 declare -ri last_full_sectors="$((last_used_bytes / sector_size))"
-dd skip="${starts[i]}" count="${last_full_sectors}" status=none <&3 ||
+dd skip="${starts[i]}" count="$last_full_sectors" status=none <&3 ||
     die "can't read $last_full_sectors sectors at ${starts[i]} (row $i)"
 
 # Read whatever remaining used data are stored in the last extent.
@@ -202,6 +204,6 @@ declare -ri last_full_bytes="$((last_used_bytes - trailing_bytes))"
 dd bs=1 skip="$last_full_bytes" count="$trailing_bytes" status=none <&3 ||
     die "can't read $trailing_bytes bytes at $last_full_bytes bytes (end)"
 
-exec 3<&- || die "can't close device node for disk $major:0"
+exec 3<&- || die "can't close device node for disk $dev_major:0"
 
 msg 'Stitching completed.'
